### ISSUE TITLE
This socket has been ended by the other party [JIRA: CLIENTS-712]

### ISSUE THREAD

**Issue by dmitrIron** [basho/riak-nodejs-client#130]
Hi, we get this error on massive set/get (about 100 concurrent connections)

```
error: [RiakConnection] (****.com:8087) Error: This socket has been ended by the other party
at Socket.writeAfterFIN [as write] (net.js:268:12)
at RiakConnection.execute (/var/www/dyno/node_modules/basho-riak-client/lib/core/riakconnection.js:354:26)
at RiakNode.execute (/var/www/dyno/node_modules/basho-riak-client/lib/core/riaknode.js:272:22)
at RoundRobinNodeManager.NodeManager.tryExecute (/var/www/dyno/node_modules/basho-riak-client/lib/core/nodemanager.js:51:18)
at RoundRobinNodeManager.executeOnNode (/var/www/dyno/node_modules/basho-riak-client/lib/core/roundrobinnodemanager.js:60:26)
at RiakCluster.execute (/var/www/dyno/node_modules/basho-riak-client/lib/core/riakcluster.js:223:38)
Client.fetchValue (/var/www/dyno/node_modules/basho-riak-client/lib/client.js:208:18)
Client.tryCatcher (/var/www/dyno/node_modules/bluebird/js/release/util.js:11:23)
at Client.ret [as fetchValueAsync] (eval at <anonymous>
```

What may be the reason of this error?
Tnx.

**Comment by lukebakken** [comment]
* When you say "massive", can you quantify it more? Are you referring to object size, or just the number of simultaneous operations?
* Can you correlate this error with errors or other log entries from your Riak nodes?
* Are you monitoring [Riak statistics](http://docs.basho.com/riak/latest/ops/running/stats-and-monitoring/)? If so, can you provide access to stat graphs during one of these events?
