### ISSUE TITLE
1.2.0 require('basho-riak-client') fails [JIRA: CLIENTS-403]

### ISSUE THREAD

**Issue by EvanOxfeld** [basho/riak-nodejs-client#59]
I can't require the `1.2.0` version of this module due to the below error. I did not have this issue with `1.1.3`.

```sh
Error: Cannot find module './lib/client'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/private/tmp/node_modules/basho-riak-client/index.js:17:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by lukebakken** [comment]
Hi @EvanOxfeld 

I made some changes to `package.json` that inadvertently left out `lib/client.js`. I just released version 1.2.1 which fixes this. Thank you for bringing this to our attention.

https://github.com/basho/riak-nodejs-client/releases/tag/v1.2.1

https://www.npmjs.com/package/basho-riak-client
